apiVersion: v1
kind: Service
metadata:
  name: explorecali-app-service
spec:
  selector:
    app: explorecali-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000